changelog:
  categories:
    - title: Breaking Changes
      labels: [breaking]
    - title: Features
      labels: [feature, enhancement]
    - title: Fixes
      labels: [fix, bug]
    - title: Documentation
      labels: [docs, documentation]
    - title: Other Changes
      labels: ['*']
