"""XQuery for MarkLogic: function builders, CTS queries and the expression compiler.

Import the cts, fn, xdmp and xs builders from this namespace and execute
composed expressions with ml.eval.expression. CTS query constructors return
the CtsQuery types exported here, which also serialize locally as search
criteria for ml.search.

This package depends on mlclient.search only for the serialization contract it
implements; mlclient.search never imports this package.
"""

from mlclient.xquery._cts import Cts
from mlclient.xquery._cts_query import (
    CTS_NS_URI,
    AfterQuery,
    AndNotQuery,
    AndQuery,
    BeforeQuery,
    BoostQuery,
    Box,
    Circle,
    CollectionQuery,
    ColumnRangeQuery,
    CtsQuery,
    DirectoryQuery,
    DocumentFormatQuery,
    DocumentFragmentQuery,
    DocumentPermissionQuery,
    DocumentQuery,
    DocumentRootQuery,
    ElementAttributePairGeospatialQuery,
    ElementAttributeRangeQuery,
    ElementAttributeValueQuery,
    ElementAttributeWordQuery,
    ElementChildGeospatialQuery,
    ElementGeospatialQuery,
    ElementPairGeospatialQuery,
    ElementQuery,
    ElementRangeQuery,
    ElementValueQuery,
    ElementWordQuery,
    FalseQuery,
    FieldRangeQuery,
    FieldValueQuery,
    FieldWordQuery,
    GeospatialRegionQuery,
    JsonPropertyChildGeospatialQuery,
    JsonPropertyGeospatialQuery,
    JsonPropertyPairGeospatialQuery,
    JsonPropertyRangeQuery,
    JsonPropertyScopeQuery,
    JsonPropertyValueQuery,
    JsonPropertyWordQuery,
    LocksFragmentQuery,
    LsqtQuery,
    NearQuery,
    NotInQuery,
    NotQuery,
    OrQuery,
    PathGeospatialQuery,
    PathRangeQuery,
    Period,
    PeriodCompareQuery,
    PeriodRangeQuery,
    Point,
    Polygon,
    PropertiesFragmentQuery,
    RangeQuery,
    RegisteredQuery,
    ReverseQuery,
    RuntimeQuery,
    SimilarQuery,
    TripleRangeQuery,
    TrueQuery,
    WordQuery,
)
from mlclient.xquery._fn import Fn
from mlclient.xquery._xdmp import Xdmp
from mlclient.xquery._xs import Xs
from mlclient.xquery.expressions import (
    AtomicValue,
    NodeInput,
    PythonNode,
    DatabaseRoot,
    FunctionCall,
    Index,
    ModuleFunctionCall,
    NamespaceMap,
    Path,
    Range,
    ResultXPath,
    XqyCompilationContext,
    XqyExpression,
    XqySequence,
    as_searchable_expression,
    namespace_bindings,
    xpath,
)

LOCAL_NS_URI = "http://www.w3.org/2005/xquery-local-functions"
"""Namespace URI for XQuery functions and variables with the local prefix."""

cts = Cts()
fn = Fn()
xdmp = Xdmp()
xs = Xs()

__all__ = [
    "CTS_NS_URI",
    "LOCAL_NS_URI",
    "AfterQuery",
    "AndNotQuery",
    "AndQuery",
    "AtomicValue",
    "BeforeQuery",
    "BoostQuery",
    "Box",
    "Circle",
    "CollectionQuery",
    "ColumnRangeQuery",
    "Cts",
    "CtsQuery",
    "DatabaseRoot",
    "DirectoryQuery",
    "DocumentFormatQuery",
    "DocumentFragmentQuery",
    "DocumentPermissionQuery",
    "DocumentQuery",
    "DocumentRootQuery",
    "ElementAttributePairGeospatialQuery",
    "ElementAttributeRangeQuery",
    "ElementAttributeValueQuery",
    "ElementAttributeWordQuery",
    "ElementChildGeospatialQuery",
    "ElementGeospatialQuery",
    "ElementPairGeospatialQuery",
    "ElementQuery",
    "ElementRangeQuery",
    "ElementValueQuery",
    "ElementWordQuery",
    "FalseQuery",
    "FieldRangeQuery",
    "FieldValueQuery",
    "FieldWordQuery",
    "Fn",
    "FunctionCall",
    "GeospatialRegionQuery",
    "Index",
    "JsonPropertyChildGeospatialQuery",
    "JsonPropertyGeospatialQuery",
    "JsonPropertyPairGeospatialQuery",
    "JsonPropertyRangeQuery",
    "JsonPropertyScopeQuery",
    "JsonPropertyValueQuery",
    "JsonPropertyWordQuery",
    "LocksFragmentQuery",
    "LsqtQuery",
    "ModuleFunctionCall",
    "NamespaceMap",
    "NearQuery",
    "NodeInput",
    "NotInQuery",
    "NotQuery",
    "OrQuery",
    "Path",
    "PathGeospatialQuery",
    "PathRangeQuery",
    "Period",
    "PeriodCompareQuery",
    "PeriodRangeQuery",
    "Point",
    "Polygon",
    "PropertiesFragmentQuery",
    "PythonNode",
    "Range",
    "RangeQuery",
    "RegisteredQuery",
    "ResultXPath",
    "ReverseQuery",
    "RuntimeQuery",
    "SimilarQuery",
    "TripleRangeQuery",
    "TrueQuery",
    "WordQuery",
    "Xdmp",
    "XqyCompilationContext",
    "XqyExpression",
    "XqySequence",
    "Xs",
    "as_searchable_expression",
    "cts",
    "fn",
    "namespace_bindings",
    "xdmp",
    "xpath",
    "xs",
]
