"""The Documents HTTP Models module.

This module contains models for /v1/documents HTTP body.
It exports the following classes:

    * BodyPart
        A class representing /v1/documents body part.
    * Disposition
        A class representing /v1/documents body part Content-Disposition header.
    * BodyPartType
        An enumeration class representing /v1/documents body part types.
    * Repair
        An enumeration class representing repair levels.
    * Extract
        An enumeration class representing metadata extract types.
    * Category
        An enumeration class representing data categories.
"""

from __future__ import annotations

from enum import Enum
from typing import ClassVar, Optional, Union

from pydantic import BaseModel, Field, field_validator

from mlclient.constants import HEADER_JSON
from mlclient.models import DocumentType
from mlclient.utils import BiDict


class BodyPartType(Enum):
    """An enumeration class representing /v1/documents body part types."""

    INLINE = "inline"
    ATTACHMENT = "attachment"


class Repair(Enum):
    """An enumeration class representing repair levels."""

    NONE = "none"
    FULL = "full"


class Extract(Enum):
    """An enumeration class representing metadata extract types."""

    PROPERTIES = "properties"
    DOCUMENT = "document"


class Category(Enum):
    """An enumeration class representing data categories."""

    CONTENT = "content"
    METADATA = "metadata"
    METADATA_VALUES = "metadata-values"
    COLLECTIONS = "collections"
    PERMISSIONS = "permissions"
    PROPERTIES = "properties"
    QUALITY = "quality"


class Disposition(BaseModel):
    """A class representing /v1/documents body part Content-Disposition header."""

    model_config = {"populate_by_name": True}

    type_: BodyPartType = Field(
        description="The content type indication (inline or attachment).",
        alias="type",
    )
    category: Optional[Union[Category, list[Category]]] = Field(
        description="The category of data.",
        default=None,
    )
    repair: Optional[Repair] = Field(
        description="For an XML content part, the level of XML repair to perform. "
        "Allowed values: full (default) or none. "
        "Use full to request the server to repair malformed input XML. "
        "Use none to request the server to reject malformed input XML. "
        "If repair results in multiple root nodes, the update is rejected.",
        default=None,
    )
    filename: Optional[str] = Field(
        description="Specifies an explicit document URI. "
        "Use extension to have MarkLogic Server generate a URI instead. "
        "For a given part, filename and extension are mutually exclusive.",
        alias="uri",
        default=None,
    )
    extension: Optional[str] = Field(
        description="Specifies a URI extension to use when the document URI "
        "is generated by MarkLogic Server. "
        "The generated URI will end with '.' plus this extension. "
        "For a given part, filename and extension are mutually exclusive.",
        default=None,
    )
    directory: Optional[str] = Field(
        description="Specifies a directory prefix to use when the document URI "
        "is generated by MarkLogic Server. "
        "The directory prefix must end with '/'. "
        "If the part header includes a directory parameter, "
        "it must also include an extension parameter. "
        "For a given part, filename and directory are mutually exclusive.",
        default=None,
    )
    extract: Optional[Extract] = Field(
        description="For a binary content part, whether or not to extract metadata, "
        "and whether to store the extracted metadata as document properties"
        "or in a separate XHTML document. "
        "Allowed values: properties or document.",
        default=None,
    )
    version_id: Optional[int] = Field(
        description="When optimistic locking is enabled by setting the REST instance "
        "configuration property update-policy to version-required or "
        "version-optional, reject this request if the current version "
        "of this document does not match the version in versionId. "
        "Only applicable to content parts. "
        "Ignored if optimistic locking is not enabled. "
        "This option is equivalent to supplying a version id "
        "through the If-Match header of a single document update.",
        default=None,
    )
    temporal_document: Optional[str] = Field(
        description="The 'logical' document URI in the temporal collection specified "
        "using the temporal-collection request parameter. "
        "You can only use this parameter if the request also includes "
        "the temporal-collection parameter.",
        default=None,
    )
    format_: Optional[DocumentType] = Field(
        description="The content format (xml, json, text or binary)",
        alias="format",
        default=None,
    )

    @property
    def is_attachment(self) -> bool:
        """Whether this disposition is an attachment (document-specific part)."""
        return self.type_ == BodyPartType.ATTACHMENT

    @property
    def is_inline(self) -> bool:
        """Whether this disposition is inline (default metadata part)."""
        return self.type_ == BodyPartType.INLINE

    @classmethod
    def from_header(cls, header: str) -> Disposition:
        """Parse a raw Content-Disposition header string.

        Parameters
        ----------
        header : str
            A raw Content-Disposition header value

        Returns
        -------
        Disposition
            A parsed Disposition instance
        """
        m = _DispositionMapping
        disp_dict = {}
        for disp in header.split(m.DISP_SEP):
            key, value = cls._parse_header_part(disp)
            curr_value = disp_dict.get(key)
            if curr_value is None:
                disp_dict[key] = value
            elif not isinstance(curr_value, list):
                disp_dict[key] = [curr_value, value]
            else:
                curr_value.append(value)
        return cls(**disp_dict)

    def to_header(self) -> str:
        """Serialize this instance to a raw Content-Disposition header string.

        Returns
        -------
        str
            A raw Content-Disposition header value
        """
        m = _DispositionMapping
        parts = [self._serialize_field(key) for key in m.FIELD_ORDER]
        return m.DISP_SEP.join([p for p in parts if p is not None])

    @staticmethod
    def _parse_header_part(disp: str) -> tuple[str, str]:
        m = _DispositionMapping
        key_value_pair = disp.split(m.KEY_VALUE_SEP)
        if len(key_value_pair) == 1:
            key = None
            value = key_value_pair[0]
        else:
            key, value = key_value_pair
        key = m.DISPOSITIONS.get(key)
        if key == m.CLASS_KEY_FORMAT:
            key = m.CLASS_KEY_FORMAT_ALIAS
        value = value[1:-1] if key == m.DISP_KEY_FILENAME else value
        return key, value

    def _serialize_field(self, class_key: str) -> str | None:
        m = _DispositionMapping
        disp_value = self.model_dump().get(class_key)
        if disp_value is None:
            return None
        disp = m.DISPOSITIONS.get(class_key)

        if not isinstance(disp_value, list):
            disp_value = [disp_value]

        dispositions = []
        for value in disp_value:
            if isinstance(value, Enum):
                final_value = value.value
            elif disp == m.DISP_KEY_FILENAME:
                final_value = f'"{value}"'
            else:
                final_value = value
            disposition = final_value if disp is None else f"{disp}={final_value}"
            dispositions.append(disposition)
        return "; ".join(dispositions)


class BodyPart(BaseModel):
    """A class representing /v1/documents body part."""

    content_type: str = Field(alias="content-type", default=HEADER_JSON)
    disposition: Disposition = Field(
        alias="content-disposition",
    )
    content: Union[str, bytes, dict]

    @field_validator("disposition", mode="before")
    @classmethod
    def parse_disposition(
        cls,
        value: str | dict,
    ) -> Disposition:
        """Parse a Content-Disposition header."""
        if isinstance(value, dict):
            return Disposition(**value)
        return Disposition.from_header(value)


class _DispositionMapping:
    """Internal mapping between Disposition fields and HTTP header params."""

    DISP_SEP = "; "
    KEY_VALUE_SEP = "="
    CLASS_KEY_TYPE = "type_"
    CLASS_KEY_CATEGORY = "category"
    CLASS_KEY_REPAIR = "repair"
    CLASS_KEY_FILENAME = "filename"
    CLASS_KEY_EXTENSION = "extension"
    CLASS_KEY_DIRECTORY = "directory"
    CLASS_KEY_EXTRACT = "extract"
    CLASS_KEY_VERSION_ID = "version_id"
    CLASS_KEY_TEMPORAL_DOC = "temporal_document"
    CLASS_KEY_FORMAT = "format_"
    CLASS_KEY_FORMAT_ALIAS = "format"
    DISP_KEY_TYPE = None
    DISP_KEY_CATEGORY = CLASS_KEY_CATEGORY
    DISP_KEY_REPAIR = CLASS_KEY_REPAIR
    DISP_KEY_FILENAME = CLASS_KEY_FILENAME
    DISP_KEY_EXTENSION = CLASS_KEY_EXTENSION
    DISP_KEY_DIRECTORY = CLASS_KEY_DIRECTORY
    DISP_KEY_EXTRACT = CLASS_KEY_EXTRACT
    DISP_KEY_VERSION_ID = "versionId"
    DISP_KEY_TEMPORAL_DOC = "temporal-document"
    DISP_KEY_FORMAT = CLASS_KEY_FORMAT_ALIAS
    DISPOSITIONS = BiDict(
        {
            CLASS_KEY_TYPE: DISP_KEY_TYPE,
            CLASS_KEY_CATEGORY: DISP_KEY_CATEGORY,
            CLASS_KEY_REPAIR: DISP_KEY_REPAIR,
            CLASS_KEY_FILENAME: DISP_KEY_FILENAME,
            CLASS_KEY_EXTENSION: DISP_KEY_EXTENSION,
            CLASS_KEY_DIRECTORY: DISP_KEY_DIRECTORY,
            CLASS_KEY_EXTRACT: DISP_KEY_EXTRACT,
            CLASS_KEY_VERSION_ID: DISP_KEY_VERSION_ID,
            CLASS_KEY_TEMPORAL_DOC: DISP_KEY_TEMPORAL_DOC,
            CLASS_KEY_FORMAT: DISP_KEY_FORMAT,
        },
    )
    FIELD_ORDER: ClassVar[list] = [
        CLASS_KEY_TYPE,
        CLASS_KEY_FILENAME,
        CLASS_KEY_CATEGORY,
        CLASS_KEY_EXTENSION,
        CLASS_KEY_DIRECTORY,
        CLASS_KEY_REPAIR,
        CLASS_KEY_EXTRACT,
        CLASS_KEY_VERSION_ID,
        CLASS_KEY_TEMPORAL_DOC,
        CLASS_KEY_FORMAT,
    ]
