"""The ML Client Constants module."""

from __future__ import annotations

# REQUEST METHODS
METHOD_GET = "GET"
METHOD_HEAD = "HEAD"
METHOD_POST = "POST"
METHOD_PUT = "PUT"
METHOD_DELETE = "DELETE"

# HEADERS
HEADER_NAME_ACCEPT = "Accept"
HEADER_NAME_CONTENT_LENGTH = "Content-Length"
HEADER_NAME_CONTENT_TYPE = "Content-Type"
HEADER_NAME_CONTENT_DISP = "Content-Disposition"
HEADER_NAME_PRIMITIVE = "X-Primitive"
HEADER_NAME_ML_DOCUMENT_FORMAT = "vnd.marklogic.document-format"

HEADER_MULTIPART_MIXED = "multipart/mixed"
HEADER_XML = "application/xml"
HEADER_JSON = "application/json"
HEADER_X_WWW_FORM_URLENCODED = "application/x-www-form-urlencoded"
HEADER_HTML = "text/html"
HEADER_PLAIN_TEXT = "text/plain"

HEADER_PRIMITIVE_STRING = "string"
HEADER_PRIMITIVE_INTEGER = "integer"
HEADER_PRIMITIVE_DECIMAL = "decimal"
HEADER_PRIMITIVE_BOOLEAN = "boolean"
HEADER_PRIMITIVE_DATE = "date"
HEADER_PRIMITIVE_DATE_TIME = "dateTime"
HEADER_PRIMITIVE_DOCUMENT_NODE = "document-node()"

# APP SERVERS
APP_SERVICES_PORT = 8000
MANAGE_PORT = 8002
ADMIN_PORT = 8001
HEALTH_PORT = 7997
DEFAULT_APP_SERVERS = (
    {"id": "app-services", "rest": True},
    {"id": "manage", "port": MANAGE_PORT},
    {"id": "admin", "port": ADMIN_PORT},
    {"id": "health", "port": HEALTH_PORT, "auth": "app"},
)

# PATHS
ML_CLIENT_DIR = ".mlclient"

__all__ = [
    "ADMIN_PORT",
    "APP_SERVICES_PORT",
    "DEFAULT_APP_SERVERS",
    "HEADER_HTML",
    "HEADER_JSON",
    "HEADER_MULTIPART_MIXED",
    "HEADER_NAME_ACCEPT",
    "HEADER_NAME_CONTENT_DISP",
    "HEADER_NAME_CONTENT_LENGTH",
    "HEADER_NAME_CONTENT_TYPE",
    "HEADER_NAME_PRIMITIVE",
    "HEADER_PLAIN_TEXT",
    "HEADER_PRIMITIVE_BOOLEAN",
    "HEADER_PRIMITIVE_DECIMAL",
    "HEADER_PRIMITIVE_DOCUMENT_NODE",
    "HEADER_PRIMITIVE_INTEGER",
    "HEADER_PRIMITIVE_STRING",
    "HEADER_XML",
    "HEADER_X_WWW_FORM_URLENCODED",
    "HEALTH_PORT",
    "MANAGE_PORT",
    "METHOD_DELETE",
    "METHOD_GET",
    "METHOD_HEAD",
    "METHOD_POST",
    "METHOD_PUT",
    "ML_CLIENT_DIR",
]
