name: Create a coverage report (INTEGRATION TESTS)

on: [pull_request]
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    services:
      marklogic:
        image: marklogicdb/marklogic-db:latest-10.0
        ports:
          - 8000:8000
          - 8001:8001
          - 8002:8002
        env:
          MARKLOGIC_INIT: true
          MARKLOGIC_ADMIN_USERNAME: admin
          MARKLOGIC_ADMIN_PASSWORD: admin

    steps:
      - name: Sleep for 45 seconds
        run: sleep 45s
        shell: bash

      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install MLClient with poetry
        run: |
          make install

      - name: Create test reports
        run: |
          poetry run pytest --junitxml=pytest.xml --cov=mlclient/clients tests/integration | tee output.txt

      - name: Put an overall test & coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          title: Code Coverage Report (INTEGRATION TESTS)
          badge-title: Code Coverage
          pytest-coverage-path: output.txt
          junitxml-path: pytest.xml
          junitxml-title: Integration Test Results
          unique-id-for-comment: integration-tests
