name: Test MLClient (INTEGRATION)

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      marklogic:
        image: marklogicdb/marklogic-db:latest-10.0
        ports:
          - 8000:8000
          - 8001:8001
          - 8002:8002
        env:
          MARKLOGIC_INIT: true
          MARKLOGIC_ADMIN_USERNAME: admin
          MARKLOGIC_ADMIN_PASSWORD: admin

    steps:
      - name: Sleep for 45 seconds
        run: sleep 45s
        shell: bash

      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install MLClient with poetry
        run: |
          make install

      - name: Test code with pytest
        run: poetry run pytest tests/integration/
