name: Lint MLClient

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MLClient with poetry
        run: |
          pip install poetry==2.2.0
          poetry install

      - name: Lint with Ruff
        run: poetry run ruff check --output-format=github .
