name: Test MLClient

on: [push]
jobs:
  test-python-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    services:
      marklogic:
        image: marklogicdb/marklogic-db:latest-10.0
        ports:
          - 8000:8000
          - 8001:8001
          - 8002:8002
        env:
          MARKLOGIC_INIT: true
          MARKLOGIC_ADMIN_USERNAME: admin
          MARKLOGIC_ADMIN_PASSWORD: admin

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install MLClient with poetry
        run: |
          make install

      - name: Test code with pytest
        run: poetry run pytest tests/
